name: Publish

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    name: Go Version ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3

      - name: Fake build
        run: |
          mkdir dist
          cd dist
          echo -en "12345" > output1
          echo -en "abcde" > output2

      - name: "Generate hashes"
        id: hash
        run: |
          cd dist && echo "hashes=$(sha256sum * | base64 -w0)" >> $GITHUB_OUTPUT

      - name: "Upload dists"
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: "dist"
          path: "dist/"
          if-no-files-found: error


  provenance:
    needs: [build]
    permissions:
      actions: read
      contents: write
      id-token: write # Needed to access the workflow's OIDC identity.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: true

  provenance-sigstore:
    needs: ["build", "provenance"]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
    steps:
      - name: install
        run: |
          python -m pip install sigstore requests
          ls -l
          pwd
          echo -en "12345" > output1
          echo -en "abcde" > output2

      - name: "Download dists"
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: "dist"
          path: "dist/"

      - uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: dist/output1 dist/output2

  publish-to-github:
    name: "Publish to github"
    needs: ["build", "provenance", "provenance-sigstore"]
    permissions:
      contents: write
      id-token: write
    runs-on: "ubuntu-latest"
    environment:
      name: "publish"

    steps:
      - name: "Download dists"
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: "dist"
          path: "dist/"

      - name: "Upload dists to GitHub Release"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh release upload ${{ github.ref_name }} dist/* --repo ${{ github.repository }}
